### ISSUE TITLE
openfeint support in ios?

### ISSUE THREAD

**Issue by liccowee** [marmalade/openfeint#1]
Does the openfeint source code provided support in ios?

**Comment by faizann** [comment]
Hi

Just pushed OpenFeint extension code to this repo. It is called s3eNOpenFeint and a sample app called HelloWorld_s3eNOpenFeint is attached.

**Comment by faizann** [comment]
iOS support is enabled in s3eNOpenFeint extension. Kindly use that.

**Comment by liccowee** [comment]
Thanks for your information..xD
