### ISSUE TITLE
Game freezes after calling s3eNOFinitializeWithProductKey

### ISSUE THREAD

**Issue by ndarwiche** [marmalade/openfeint#10]
Hello,
i'm trying to run s3eHelloWorld example , and it always freezes after calling s3eNOFinitializeWithProductKey.
i tried that on iOS and android and I've got the same result.

thank you

**Comment by faizann** [comment]
I have noticed that openfeint takes a while to startup in case the mobile is offline or internet connection is bad. Is this the case with you?

**Comment by ndarwiche** [comment]
no it's a fast connection, and it actually crashes on android "it gives the message :The application s3eHelloWorld (process com.mycompany.s3ehelloworld) ha stopped unexpectedly, please try again."

**Comment by faizann** [comment]
Which device and which version of Android is it?
I have tested on Nexus S and Galaxy S2. 
I will test in a few days again. Can you debug the system and see what is going wrong?

It could be that not all assets/resources are in the package and thus causing it to crash. Check your intermediate files for openfeint resources.

**Comment by ndarwiche** [comment]
you're right, it wasn't copying openfeint resources to intermediate files. 
i tried it in my project without "if {{defined I3D_OS_IPHONE}}" and it works :)
thank you
