### ISSUE TITLE
Build for iOS

### ISSUE THREAD

**Issue by rodburns** [marmalade/openfeint#4]
Can you help with this conflict with s3eFacebook?
http://www.madewithmarmalade.com/devnet/forum/6774
Thanks,
Rod.

**Comment by faizann** [comment]
I see the issue. Both OpenFeint and s3eFacebook use same Facebook SDK and that causes duplicate symbols. 
I will look at it and find a solution. Might have to rename some parts in Facebook SDK itself.

**Comment by faizann** [comment]
Hi

Updated code to use OpenFeint 2.12. It resolves the issue of Facebook conflicts.

**Comment by rodburns** [comment]
Great, thanks.
