### ISSUE TITLE
Add iphone deployment option in s3eNOpenFeint.mkf

### ISSUE THREAD

**Issue by nascode** [marmalade/openfeint#7]
Hello, thank you for your effort integrating openfeint into Marmalade!

I tried to integrate OpenFeint in iOS and found out that i must add additional iphone deployment option.

Current  HelloWorld_s3eNOpenFeint example's deployment mkb:

["Default"]
assets='Default'
iphone-appid='com.nerdiacs.funkyracing'
iphone-link-libs='s3eFacebook'
iphone-link-opts='-weak_framework CoreText -weak_framework UIKit -weak_framework Security -weak_framework AddressBook -weak_framework AddressBookUI -weak_framework MapKit -lsqlite3.0'
iphone-no-splash=1
iphone-nosign=0
iphone-signing-identity='iPhone Developer'
splashscreen-auto-onblack=1

Looks like iphone-link-libs and iphone-link-libdirs option for s3eNOpenFeint is missing, then i check the extension's mkf 

deployments
{
    android-external-jars="lib/android/s3eNOpenFeint.jar"
    android-external-jars="source/android/OpenFeint.jar"
    android-so="lib/android/libs3eNOpenFeint.so"
}

No iphone-link-libs and iphone-link-libdirs option in s3eNOpenFeint.mkf defined.

I fix s3eNOpenFeint.mkf into:

deployments
{
  android-external-jars="lib/android/s3eNOpenFeint.jar"
  android-external-jars="source/android/OpenFeint.jar"
  android-so="lib/android/libs3eNOpenFeint.so"
  iphone-link-libs=s3eNOpenFeint
  iphone-link-libdirs=lib/iphone
  iphone-link-opts='-weak_framework CoreText -weak_framework UIKit -weak_framework Security -weak_framework AddressBook -weak_framework AddressBookUI -weak_framework MapKit -lsqlite3.0'
}

After that  i could clear up my app's mkb into:

 ["Default"]
iphone-appid='com.nerdiacs.funkyracing'

Hope this help anyone tried to integrate this extension

**Comment by faizann** [comment]
Thanks.
I screwed up mkb of HelloWorld when I started focusing on Android version. Will fix MKF/MKB proper in next push.
